import React from "react";
import { Card, Button, Tag, Space, Typography } from "antd";
import { ThunderboltOutlined, CheckCircleOutlined, ArrowRightOutlined } from "@ant-design/icons";
import { useNavigate } from "react-router-dom";

const { Text } = Typography;

export const DailyQuizWidget = ({ quiz, completed = false, score = null, loading = false }) => {
  const navigate = useNavigate();

  return (
    <Card
      className="glass-card glass-card-hover"
      bordered={false}
      style={{
        background: completed
          ? "linear-gradient(135deg, rgba(16, 185, 129, 0.12) 0%, rgba(16, 185, 129, 0.04) 100%)"
          : "linear-gradient(135deg, rgba(99, 102, 241, 0.12) 0%, rgba(139, 92, 246, 0.04) 100%)",
        border: completed
          ? "1px solid rgba(16, 185, 129, 0.25)"
          : "1px solid rgba(99, 102, 241, 0.25)",
        borderRadius: 12,
        height: "100%",
      }}
      bodyStyle={{ padding: "20px 24px" }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div
            style={{
              width: 38,
              height: 38,
              borderRadius: 10,
              background: completed ? "#10b981" : "#6366f1",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              color: "#fff",
              fontSize: 18,
            }}
          >
            {completed ? <CheckCircleOutlined /> : <ThunderboltOutlined />}
          </div>
          <div>
            <h4 style={{ margin: 0, fontSize: 16, fontWeight: 700 }}>
              {completed ? "Daily Quiz Completed" : "Today's AI Practice Quiz"}
            </h4>
            <Text style={{ fontSize: 12, color: "var(--text-muted)" }}>
              {completed ? "Great work! Streak maintained." : "5 targeted questions generated by AI"}
            </Text>
          </div>
        </div>

        {completed ? (
          <Tag color="success" style={{ fontWeight: 700, borderRadius: 6, fontSize: 13, padding: "2px 8px" }}>
            Score: {score !== null ? `${Math.round(score)}%` : "100%"}
          </Tag>
        ) : (
          <Tag color="processing" style={{ fontWeight: 700, borderRadius: 6, fontSize: 12 }}>
            Ready
          </Tag>
        )}
      </div>

      <div style={{ marginTop: 14 }}>
        {quiz?.topics && quiz.topics.length > 0 && (
          <div style={{ marginBottom: 16 }}>
            <span style={{ fontSize: 12, color: "var(--text-secondary)", fontWeight: 600, display: "block", marginBottom: 6 }}>
              Target Concepts:
            </span>
            <Space wrap size={[4, 6]}>
              {quiz.topics.map((topic, i) => (
                <Tag key={i} color="blue" style={{ borderRadius: 4, fontSize: 11, margin: 0 }}>
                  {topic}
                </Tag>
              ))}
            </Space>
          </div>
        )}

        <Button
          type={completed ? "default" : "primary"}
          icon={completed ? <CheckCircleOutlined /> : <ArrowRightOutlined />}
          onClick={() => navigate("/student/quiz")}
          loading={loading}
          block
          style={{
            borderRadius: 8,
            fontWeight: 600,
            marginTop: 4,
          }}
        >
          {completed ? "Review Quiz Results" : "Start Today's Quiz"}
        </Button>
      </div>
    </Card>
  );
};

export default DailyQuizWidget;
